AllCops:
  Exclude:
    - './file.rb'
    - './correct_syntax.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Migration/DepartmentName:
  Enabled: false

Style/Documentation: 
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false